package com.onevillage.backend.common;

public enum ErrorCode {
    VALIDATION_ERROR,
    NOT_FOUND,
    UNAUTHORIZED,
    FORBIDDEN,
    CONFLICT,
    BAD_REQUEST,
    TERMS_UPDATE_REQUIRED,
    EMAIL_ALREADY_REGISTERED,
    EMAIL_NOT_VERIFIED,
    INVALID_CREDENTIALS,
    ACCOUNT_SUSPENDED,
    USER_BLOCKED,
    INTERNAL_ERROR
}
